from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(
        description="List of sources used to generate the answer"
    )
